# Generated by Django 4.1.2 on 2022-10-31 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliance_type', models.CharField(max_length=16)),
                ('appliance_brand', models.CharField(max_length=16)),
                ('appliance_model', models.CharField(max_length=16)),
                ('appliance_sn', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=16)),
                ('last_name', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=32)),
                ('phone_number', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('component_code', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('component_qty', models.IntegerField()),
                ('component_price', models.IntegerField()),
                ('component_description', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Ingress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingress_date', models.DateField()),
                ('state', models.IntegerField()),
                ('quotation', models.IntegerField()),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.appliance')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.client')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_type', models.CharField(max_length=16)),
                ('user_username', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('user_first_name', models.CharField(max_length=16)),
                ('user_last_name', models.CharField(max_length=16)),
                ('user_password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Used_Parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('component_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.component')),
                ('ingress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.ingress')),
            ],
        ),
        migrations.CreateModel(
            name='Ingress_Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateField()),
                ('update_state', models.IntegerField()),
                ('ingress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.ingress')),
            ],
        ),
        migrations.AddField(
            model_name='ingress',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.user'),
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory_type', models.CharField(max_length=16)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.appliance')),
            ],
        ),
    ]
