# Generated by Django 4.1.2 on 2022-11-01 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_user_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingress',
            name='accessories',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='ingress',
            name='diagnosis',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='ingress',
            name='failure_description',
            field=models.CharField(default='NaN', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingress',
            name='inspection_status',
            field=models.CharField(default='NaN', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingress_update',
            name='update_description',
            field=models.CharField(default='NaN', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingress',
            name='technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.user'),
        ),
        migrations.DeleteModel(
            name='Accessory',
        ),
    ]
